# Generated by Django 4.2.1 on 2023-05-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_admins_acation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminsHasDep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=10)),
                ('name_file', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Dname', models.CharField(max_length=25)),
                ('name_file', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('index', models.TextField()),
                ('files', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserhasDep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('name_file', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='admins',
            name='acation',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='id',
        ),
        migrations.AlterField(
            model_name='admins',
            name='Password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admins',
            name='UserName',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
