# Generated by Django 4.2.1 on 2023-05-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_adminshasdep_department_user_userhasdep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='e_mail',
            field=models.CharField(max_length=50),
        ),
    ]
